import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Optional: For fallback fonts
import "./globals.css";

// Importing Poppins font from Google Fonts
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${poppins.className} antialiased `}>{children}</body>
    </html>
  );
}
