name: CI/CD – Deploy to Hostinger VPS

# ──────────────────────────────
# Trigger: every push to main
# ──────────────────────────────
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Grab the repo at the commit that triggered the workflow
      - name: Checkout code
        uses: actions/checkout@v4

      # Use the same Node version your server runs (v22)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # CI build – fail early if install or build breaks
      - name: Install & build
        run: |
          npm ci
          npm run build

      # Deploy to VPS via SSH
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # go to the live folder
            cd /var/www/thefreelancepm || exit 1
            # pull latest code
            git pull origin main
            # install prod deps
            npm ci
            # build next.js in prod mode
            npm run build
            # hot-reload if process exists, otherwise start
            pm2 reload freelancepm --update-env || \
              pm2 start npm --name freelancepm -- start
